name: Refresh Catalog (daily)
on:
 schedule:
 - cron: '0 13 * * *'
 workflow_dispatch:
permissions:
 contents: write
jobs:
 refresh:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v4
 - uses: actions/setup-node@v4
 with:
 node-version-file: .nvmrc
 cache: 'npm'
 - run: npm ci
 - name: Fetch catalog via Walmart API (if creds set)
 env:
 WALMART_CLIENT_ID: ${{ secrets.WALMART_CLIENT_ID }}
 WALMART_CLIENT_SECRET: ${{ secrets.WALMART_CLIENT_SECRET }}
 WALMART_QUERIES: ${{ vars.WALMART_QUERIES || 'Electric Bike' }}
 run: node scripts/fetch_walmart_catalog.mjs
 - name: Create Pull Request with changes
 uses: peter-evans/create-pull-request@v6
 with:
 commit-message: "chore(data): refresh walmart catalog"
 title: "chore(data): refresh walmart catalog"
 body: "Automated daily refresh of data/walmart_products.json"
 branch: chore/refresh-data